In [2]:
import numpy as np
import pandas as pd
import matplotlib

In [3]:
df=pd.read_csv('food_coded.csv')

In [4]:
print(df.isnull().sum())

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [5]:
df

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [6]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [7]:
df["calories_day"].fillna(df['calories_day'].median(),inplace=True)

C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\3881181144.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["calories_day"].fillna(df['calories_day'].median(),inplace=True)

In [8]:
df["type_sports"] = df["type_sports"].fillna(method="ffill")

C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\3481071830.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["type_sports"] = df["type_sports"].fillna(method="ffill")

In [9]:
null_cols = df.columns[df.isnull().any()]
print(null_cols)

Index(['GPA', 'calories_scone', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'cuisine', 'diet_current',
       'drink', 'eating_changes', 'employment', 'exercise', 'father_education',
       'father_profession', 'fav_cuisine', 'fav_food', 'food_childhood',
       'healthy_meal', 'ideal_diet', 'income', 'life_rewarding',
       'marital_status', 'meals_dinner_friend', 'mother_education',
       'mother_profession', 'on_off_campus', 'persian_food',
       'self_perception_weight', 'soup', 'sports', 'tortilla_calories',
       'weight'],
      dtype='object')

In [10]:
df["comfort_food"] = df["comfort_food"].fillna(method="ffill")
df["comfort_food_reasons"] = df["comfort_food_reasons"].fillna(method="ffill")
df["diet_current"] = df["diet_current"].fillna(method="ffill")
df["eating_changes"] = df["eating_changes"].fillna(method="ffill")
 
df["father_profession"] = df["father_profession"].fillna(method="ffill")
df["fav_cuisine"] = df["fav_cuisine"].fillna(method="ffill")
df["food_childhood"] = df["food_childhood"].fillna(method="ffill")
df["healthy_meal"] = df["healthy_meal"].fillna(method="ffill")

df["ideal_diet"] = df["ideal_diet"].fillna(method="ffill")
df["meals_dinner_friend"] = df["meals_dinner_friend"].fillna(method="ffill")
df["mother_profession"] = df["mother_profession"].fillna(method="ffill")

C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["comfort_food"] = df["comfort_food"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["comfort_food_reasons"] = df["comfort_food_reasons"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["diet_current"] = df["diet_current"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["eating_changes"] = df["eating_changes"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["father_profession"] = df["father_profession"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["fav_cuisine"] = df["fav_cuisine"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["food_childhood"] = df["food_childhood"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["healthy_meal"] = df["healthy_meal"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["ideal_diet"] = df["ideal_diet"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:12: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["meals_dinner_friend"] = df["meals_dinner_friend"].fillna(method="ffill")
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\879442837.py:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["mother_profession"] = df["mother_profession"].fillna(method="ffill")

In [11]:
df.select_dtypes(include="object").columns

Index(['GPA', 'comfort_food', 'comfort_food_reasons', 'diet_current',
       'eating_changes', 'father_profession', 'fav_cuisine', 'food_childhood',
       'healthy_meal', 'ideal_diet', 'meals_dinner_friend',
       'mother_profession', 'type_sports', 'weight'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           125 non-null    float64
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          125 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                125 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             125 non-null    object
 25  fav_cuisine                   125 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           125 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             125 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   125 non-null    object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        125 non-null    float64
dtypes: float64(22), int64(27), object(12)
memory usage: 59.7+ KB

In [12]:
#change to numarec by the hewlp of pd.to_numarec
df["GPA"] = pd.to_numeric(df["GPA"], errors="coerce")

In [13]:
df['weight']=pd.to_numeric(df['weight'],errors='coerce')

In [14]:
df['weight'].fillna(df['weight'].mean(),inplace=True)

C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\463544172.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight'].fillna(df['weight'].mean(),inplace=True)

In [15]:
df['GPA'].unique()

array([2.4  , 3.654, 3.3  , 3.2  , 3.5  , 2.25 , 3.8  , 3.904, 3.4  ,
       3.6  , 3.1  ,   nan, 4.   , 2.2  , 3.87 , 3.7  , 3.9  , 2.8  ,
       3.   , 3.65 , 3.89 , 2.9  , 3.605, 3.83 , 3.292, 3.35 , 2.6  ,
       3.67 , 3.73 , 2.71 , 3.68 , 3.75 , 3.92 , 3.77 , 3.63 , 3.882])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           120 non-null    float64
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          125 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                125 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             125 non-null    object
 25  fav_cuisine                   125 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           125 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             125 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   125 non-null    object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        125 non-null    float64
dtypes: float64(22), int64(27), object(12)
memory usage: 59.7+ KB

In [26]:
df

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.400,2,1,430,3.0,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187.0
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
2,3.300,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,158.5
3,3.200,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,none,3,1,1315,158.5
4,3.500,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.500,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,2.0,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156.0
121,3.000,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,2.0,...,1.0,1.0,4,940.0,500,basketball,5,2,1315,180.0
122,3.882,1,1,720,3.0,420.0,1,"rice, potato, seaweed soup",sadness,2.0,...,1.0,2.0,5,580.0,690,none,4,2,1315,120.0
123,3.000,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",2.0,...,2.0,2.0,1,940.0,500,none,3,1,1315,135.0
124,3.900,1,1,430,3.0,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",2.0,...,1.0,2.0,2,725.0,345,none,4,2,575,135.0

In [18]:
df['GPA'].fillna(df["GPA"].mean(),inplace=True)

C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\1210732238.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GPA'].fillna(df["GPA"].mean(),inplace=True)

In [19]:
print(df)

       GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0    2.400       2          1               430           3.0           315.0
1    3.654       1          1               610           3.0           420.0
2    3.300       1          1               720           4.0           420.0
3    3.200       1          1               430           3.0           420.0
4    3.500       1          1               720           2.0           420.0
..     ...     ...        ...               ...           ...             ...
120  3.500       1          1               610           4.0           420.0
121  3.000       1          1               265           2.0           315.0
122  3.882       1          1               720           3.0           420.0
123  3.000       2          1               720           4.0           420.0
124  3.900       1          1               430           3.0           315.0

     coffee                             comfort_food  \
0         1                                     none
1         2              chocolate, chips, ice cream
2         2          frozen yogurt, pizza, fast food
3         2         Pizza, Mac and cheese, ice cream
4         2             Ice cream, chocolate, chips
..      ...                                      ...
120       2  wine. mac and cheese, pizza, ice cream
121       2               Pizza / Wings / Cheesecake
122       1               rice, potato, seaweed soup
123       1             Mac n Cheese, Lasagna, Pizza
124       2             Chocolates, pizza, and Ritz.

                              comfort_food_reasons  \
0                            we dont have comfort
1                             Stress, bored, anger
2                                  stress, sadness
3                                          Boredom
4                       Stress, boredom, cravings
..                                             ...
120                           boredom and sadness
121                Loneliness / Homesick / Sadness
122                                        sadness
123  happiness, they are some of my favorite foods
124               hormones, Premenstrual syndrome.

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1
1                           1.0  ...   1.0     1.0          2
2                           1.0  ...   1.0     2.0          5
3                           2.0  ...   1.0     2.0          5
4                           1.0  ...   1.0     1.0          4
..                          ...  ...   ...     ...        ...
120                         NaN  ...   1.0     1.0          5
121                         NaN  ...   1.0     NaN          4
122                         NaN  ...   1.0     2.0          5
123                         NaN  ...   2.0     2.0          1
124                         NaN  ...   1.0     2.0          2

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1
1               725.0              690  Basketball            4         2
2              1165.0              500         none           5         1
3               725.0              690         none           3         1
4               940.0              500     Softball           4         2
..                ...              ...          ...         ...       ...
120             940.0              500     Softball           5         1
121             940.0              500  basketball            5         2
122             580.0              690         none           4         2
123             940.0              500         none           3         1
124             725.0              345         none           4         2

     waffle_calories  weight
0               1315   187.0
1                900   155.0
2                900   158.5
3               1315   158.5
4                760   190.0
..               ...     ...
120             1315   156.0
121             1315   180.0
122             1315   120.0
123             1315   135.0
124              575   135.0

[125 rows x 61 columns]

In [21]:
df.isnull().sum()

GPA                 0
Gender              0
breakfast           0
calories_chicken    0
calories_day        0
                   ..
type_sports         0
veggies_day         0
vitamins            0
waffle_calories     0
weight              0
Length: 61, dtype: int64

In [22]:
null_cols = df.columns[df.isnull().any()]
print(null_cols)

Index(['calories_scone', 'comfort_food_reasons_coded', 'cook', 'cuisine',
       'drink', 'employment', 'exercise', 'father_education', 'fav_food',
       'income', 'life_rewarding', 'marital_status', 'mother_education',
       'on_off_campus', 'persian_food', 'self_perception_weight', 'soup',
       'sports', 'tortilla_calories'],
      dtype='object')

In [24]:
df['calories_scone'].fillna(df["calories_scone"].median(),inplace=True)
df['comfort_food_reasons_coded'].fillna(df["comfort_food_reasons_coded"].median(),inplace=True)
df['cook'].fillna(df["cook"].median(),inplace=True)
df['cuisine'].fillna(df["cuisine"].median(),inplace=True)

df['drink'].fillna(df["drink"].median(),inplace=True)
df['employment'].fillna(df["employment"].median(),inplace=True)
df['exercise'].fillna(df["exercise"].median(),inplace=True)
df['father_education'].fillna(df["father_education"].median(),inplace=True)

df['fav_food'].fillna(df["fav_food"].median(),inplace=True)
df['income'].fillna(df["income"].median(),inplace=True)
df['life_rewarding'].fillna(df["life_rewarding"].median(),inplace=True)
df['marital_status'].fillna(df["marital_status"].median(),inplace=True)


df['mother_education'].fillna(df["mother_education"].median(),inplace=True)
df['on_off_campus'].fillna(df["on_off_campus"].median(),inplace=True)
df['persian_food'].fillna(df["persian_food"].median(),inplace=True)
df['self_perception_weight'].fillna(df["self_perception_weight"].median(),inplace=True)

df['soup'].fillna(df["soup"].median(),inplace=True)
df['sports'].fillna(df["sports"].median(),inplace=True)
df['tortilla_calories'].fillna(df["tortilla_calories"].median(),inplace=True)

C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['calories_scone'].fillna(df["calories_scone"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['comfort_food_reasons_coded'].fillna(df["comfort_food_reasons_coded"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cook'].fillna(df["cook"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cuisine'].fillna(df["cuisine"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['drink'].fillna(df["drink"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['employment'].fillna(df["employment"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['exercise'].fillna(df["exercise"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['father_education'].fillna(df["father_education"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fav_food'].fillna(df["fav_food"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['income'].fillna(df["income"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['life_rewarding'].fillna(df["life_rewarding"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['marital_status'].fillna(df["marital_status"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mother_education'].fillna(df["mother_education"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['on_off_campus'].fillna(df["on_off_campus"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['persian_food'].fillna(df["persian_food"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['self_perception_weight'].fillna(df["self_perception_weight"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['soup'].fillna(df["soup"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sports'].fillna(df["sports"].median(),inplace=True)
C:\Users\vasud\AppData\Local\Temp\ipykernel_19524\2610472110.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tortilla_calories'].fillna(df["tortilla_calories"].median(),inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           125 non-null    float64
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                125 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          125 non-null    object
 9   comfort_food_reasons_coded    125 non-null    float64
 10  cook                          125 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       125 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         125 non-null    float64
 16  eating_changes                125 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    125 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      125 non-null    float64
 23  father_education              125 non-null    float64
 24  father_profession             125 non-null    object
 25  fav_cuisine                   125 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      125 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        125 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                125 non-null    float64
 41  marital_status                125 non-null    float64
 42  meals_dinner_friend           125 non-null    object
 43  mother_education              125 non-null    float64
 44  mother_profession             125 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 125 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  125 non-null    float64
 50  self_perception_weight        125 non-null    float64
 51  soup                          125 non-null    float64
 52  sports                        125 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             125 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   125 non-null    object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        125 non-null    float64
dtypes: float64(22), int64(27), object(12)
memory usage: 59.7+ KB